### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by IsaiahPatton** [IsaiahPatton/RainbowPluginList#2]
- [ ] Bootstrap theme.
- [ ] Display plugin authors.
- [ ] Display plugin version & Minecraft version.
- [ ] Sort plugins by catagory.
- [ ] Impove JS
